const ACTION_TYPES = {
    CONVERSATION_INITIALIZED: 1,
    CONVERSATION_INITIALIZATION_DENIED: 2,
    MESSAGE_SENT: 3,
    MESSAGE_SENDING_DENIED: 4,
    BROADCAST_MESSAGE_SENT: 5,
    BROADCAST_MESSAGE_SENDING_DENIED: 6,
    USER_KICKED: 7,
    USER_KICK_DENIED: 8,
    USER_GRANTED: 9,
    USER_GRANT_DENIED: 10
}

module.exports = ACTION_TYPES